### ISSUE TITLE
Add custom classes to ngdialog-content

### ISSUE THREAD

**Issue by stefan-niedermann** [likeastore/ngDialog#148]
As a developer i want to be able to add a custom class to the ngdialog-content dom element.

Background:
I am already using some kind of "inline"-messages, with classes like "success", "warning", "info", "error",....
Now i want to integrate ngDialog in some situation - of course the look and feel should be the same.

Currently i have to do this via duplicate stylesheet:

```css
.message, .ngdialog-content {
 border: 1px solid #666;
}

.message.success, .success-template .ngdialog-content {
border-color: #099;
}

.messages.error, .error-template .ngdialog-content {
border-color: #600;
}
```
