### ISSUE TITLE
Is there any suggestion to make this modal dailog responsive?

### ISSUE THREAD

**Issue by c437** [likeastore/ngDialog#214]
Right now the .ngdialog-content {width:450px}, is it possible to pass different sizes?

**Comment by MiguelMike** [comment]
+1

**Comment by iblong2iyush** [comment]
+1

**Comment by iblong2iyush** [comment]
Or you could just use '%' instead of px.

**Comment by MiguelMike** [comment]
Try using percents in combination with max-width and max-height. Works perfectly for me.

**Comment by jmcmichael** [comment]
Yes, you can use media queries. I am compiling my css with less and bootstrap 3, so I am using their breakpoints but this same technique should work for straight CSS (although you'll have to write more cumbersome selectors):

``` css
.ngdialog.ngdialog-theme-default .ngdialog-content {
  @media (max-width: @screen-sm-min) {
    width: 100%;
    border-radius: 0;
  }
  @media (min-width: @screen-sm-min) {
    width: 90%;
  }
  @media (min-width: @screen-md-min) {
    width: @container-md - 100px;
  }
  @media (min-width: @screen-lg-min) {
    width: @container-lg - 200px;
  }
}
```
