### ISSUE TITLE
ngDialog generic stylesheet breaks all CSS animations inside dialog

### ISSUE THREAD

**Issue by w3core** [likeastore/ngDialog#294]
The `ngDialog` generic stylesheet breaks all CSS animations inside dialog when the  `disableAnimation` property is defined as `TRUE`. Looks like would be better apply it for the `ngDialog` elements only, but not for inside elements.
There is no way to override this rule to prevent animations breaking without hard code changes.

The problem is here:
```css
.ngdialog.ngdialog-disabled-animation * {
  -webkit-animation: none!important;
  animation: none!important;
}
```
This rule should to be changed to:
```css
.ngdialog.ngdialog-disabled-animation,
.ngdialog.ngdialog-disabled-animation .ngdialog-overlay,
.ngdialog.ngdialog-disabled-animation .ngdialog-content {
  -webkit-animation: none!important;
  animation: none!important;
}
```
