### ISSUE TITLE
Overlay is preventing scrollbar from functioning for large dialogs

### ISSUE THREAD

**Issue by bgse** [likeastore/ngDialog#94]
When opening a large dialog (one that would require the user to scroll in order to see all content), the overflow scrollbar is located "behind" the opaque overlay, and on most browsers cannot be interacted with.

See this screenshot, note the "greyed-out" scrollbar on the right:

![scrollbar_issue](https://cloud.githubusercontent.com/assets/8385202/4542321/81978ef4-4e20-11e4-81d9-1337ab33e0bf.png)

Firefox:
- when dialog is open, scrollbar appears to be "behind" the overlay, you cannot interact with the scrollbar, trying to do so will immediately trigger dialog close.

Chrome:
- scrollbar is not visually behind the overlay, but the interaction issue is the same as with firefox.

Safari:
- exact same problem as chrome, no direct visual effect, but no interaction

InternetExplorer11:
- scrollbar is visually behind the overlay, but interaction does work as expected, you can in fact use the scrollbar.

**Comment by TheProdigyFilippo** [comment]
Hi. This bug is closed, but it looks like it still exists. Checked on the 6680647684d43c288c0327247baf0f0278603dc1 commit. It would be nice to have this functionality working.

**Comment by TheProdigyFilippo** [comment]
Scolling when mouse pointer is on modal content works, but there is still an issue with scrolling when mouse pointer is on overlay. I tried to workaround with solution found in #63 suggested by lagr - adding ngdialog-overlay to className and set overlay to false:
```javascript
className: 'your-custom-classes ngdialog-overlay',
overlay: false,
```
It works partially, because for example in Chrome, some content shows even after few seconds (non-deterministic - sometimes rapidly, sometimes not). Content is there, but it is not visible. So I added another z-index to .ngdialog-content:
```css
.ngdialog-content {
  z-index: 10001;
}
```
to my CSS theme and it looks like problem is resolved for now. Content loads normally. But it is only workaround. Sorry that I can't give you proper sollution, but I'm not good in JS, CSS.

Cheers

**Comment by darrenshrwd** [comment]
I just took latest code and still have this issue also, it makes the dialog unusable for large content, dialog content will scroll with a mouse wheel, but of course most people use laptops.

**Comment by thbsolutions** [comment]
Still wondering why this isn't fixed yet, also have this issue :(

**Comment by egor-smirnov** [comment]
@TheProdigyFilippo @thbsolutions @daanoz if you want this fixed ASAP, please submit the PR. I am currently a bit busy to do it right now.

**Comment by leitasat** [comment]
The possible solution is changing 
```css
.ngdialog-overlay{
...
  right: 0;
...
}
```
to 
```css
.ngdialog-overlay{
...
  right: 15px;
...
}
```
but one needs to get the number '15' from a browser because the width probably depends on it. Could not come up with such a script immediately.

**Comment by faceleg** [comment]
Is this still an issue?

**Comment by darrenshrwd** [comment]
Although there are suggestions above I don't think anyone has committed a fix?...my product is still several months away so I don't have motivation to look into fixing myself (or failing that switch to another lib) yet.

**Comment by faceleg** [comment]
Thanks for replying.

If motivation strikes, know that we are waiting.

**Comment by leitasat** [comment]
@faceleg yes it is. My hack does not work properly if a popup does not need a scroll bar (transparent strip occurs)

**Comment by agungsb** [comment]
I faced the same problem but I managed to solve the problem by change this (from file ngDialog.js):

```javascript
$dialog.html((options.overlay ?
                                '<div class="ngdialog-overlay"></div><div class="ngdialog-content" role="document">' + template + '</div>' :
                                '<div class="ngdialog-content" role="document">' + template + '</div>'));
```

to:

```javascript
$dialog.html((options.overlay ?
                                '<div class="ngdialog-overlay"><div class="ngdialog-content" role="document">' + template + '</div>' :
                                '<div class="ngdialog-content" role="document">' + template + '</div></div>'));
```

I moved ngdialog-content to be the children of ngdialog-overlay. I haven't found any problem so far, but seriously, is there any reason why ngdialog-content is not the children of ngdialog-overlay at the first place?

**Comment by faceleg** [comment]
Would you submit a pr so we can get a focused review of this change going? I'd like to see his issue resolved.

**Comment by agungsb** [comment]
@faceleg I'm sorry, I'm new to Github. So I need plenty of time to submit a PR, but I already have submitted it.

**Comment by MiguelMike** [comment]
I actually think that the best option would be to either:
a) scale the dialog to fit the available real estate and enable scrolling of it's content
b) not use the dialog if its content is too large to fit within the viewport

I'd go for option A

**Comment by faceleg** [comment]
@agungsb did your PR resolve this issue?

@MiguelMike I agree that A sounds good, PR?

**Comment by MiguelMike** [comment]
@faceleg Sorry, no PR for this one. I'm using flexbox layout for dialog. This could be not something everyone would choose. [Here's a nice guide to flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

Here's some basic styling for `.dialog` and `.ngdialog-content`. Deeper elements should be styled according to indivitual needs.

 **NOTE:** Remove prefixes if you don't need cross-browser compatibility.

```css
.dialog {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1000;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-align-items: center;
    -ms-flex-align: center;
    align-items: center;
    -webkit-justify-content: center;
    -ms-flex-pack: center;
    justify-content: center;
}

.ngdialog-content {
    position: relative;
    z-index: 1000;
    background: #fff;
    -webkit-flex: 0 0 auto;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    -webkit-flex-flow: column;
    -ms-flex-flow: column;
    flex-flow: column;
    width: 100%;
    max-height: 80%;
    overflow: hidden;
    padding: 0;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    max-width: 70%;
    border-radius: 0;
```

**Comment by haikyuu** [comment]
Here is a little hack if you just need the scroll-bar to work:
```css
.ngdialog-overlay .ngdialog-overlay {
    display: none;
}
```
The overlay color is now lighter but you can change it in the same way
